spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpastudy
    username: sa
    password:
      driver-class-name: org.j2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        integration:
          envers:
            enabled: false

logging:
  level:
    org.hibernate.SQL: debug
